using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;


namespace geocoderNet.Models
{
    public class Constants
    {
        public static Regex Regex(Dictionary<string, string> dict)
        {
            return new Regex(@"\b(" + String.Join("|", dict.Keys) + "|" + String.Join("|", dict.Values) + @")\b", RegexOptions.IgnoreCase);
        }

        public static string RegexSource(Dictionary<string, string> dict)
        {
            return @"\b(" + String.Join("|", dict.Keys) + "|" + String.Join("|", dict.Values) + @")\b";
        }

        public static Regex RegexKeysOnly(Dictionary<string, string> dict)
        {
            return new Regex(@"\b(" + String.Join("|", dict.Keys) + @")\b", RegexOptions.IgnoreCase);
        }

        public static string RegexSourceKeysOnly(Dictionary<string, string> dict)
        {
            return @"\b(" + String.Join("|", dict.Keys) + @")\b";
        }



        //http://www.census.gov/geo/maps-data/data/pdfs/tiger/tgrshp2013/TGRSHP2013_TechDoc.pdf


        // The Directional constant maps compass direction words in English and
        // Spanish to their 1- or 2- letter abbreviations.  See 2008 TIGER/Line
        // technical documentation Appendix C for more details.  ** 2013 Appendix D
        public static Dictionary<string, string> Directional = new Dictionary<string, string>()
        {
            {"North"	, "N"},
            {"South"	, "S"},
            {"East"	, "E"},
            {"West"	, "W"},
            {"Northeast"	, "NE"},
            {"Northwest"	, "NW"},
            {"Southeast"	, "SE"},
            {"Southwest"	, "SW"},
            {"Norte"	, "N"},
            {"Sur"	, "S"},
            {"Este"	, "E"},
            {"Oeste"	, "O"},
            {"Noreste"	, "NE"},
            {"Noroeste"	, "NO"},
            {"Sudeste"	, "SE"},
            {"Sudoeste"	, "SO"}
        };

        // The Prefix_Qualifier constant maps feature prefix qualifiers to their
        // abbreviations. See 2008 TIGER/Line technical documentation Appendix D.  ** 2013 appendix E
        public static Dictionary<string, string> Prefix_Qualifier = new Dictionary<string, string>()
        {
            {"Alternate"	, "Alt"},
            {"Business"	, "Bus"},
            {"Bypass"	, "Byp"},
            {"Extended"	, "Exd"},
            {"Historic"	, "Hst"},
            {"Loop"	, "Lp"},
            {"Old"	, "Old"},
            {"Private"	, "Pvt"},
            {"Public"	, "Pub"},
            {"Spur"	, "Spr"},
        };

        // The Suffix_Qualifier constant maps feature suffix qualifiers to their
        // abbreviations. See 2008 TIGER/Line technical documentation Appendix D. ** 2013 appendix E
        // *** These can also be prefixes  ****
        public static Dictionary<string, string> Suffix_Qualifier = new Dictionary<string, string>()
        {
            {"Access"	, "Acc"},
            {"Alternate"	, "Alt"},
            {"Business"	, "Bus"},
            {"Bypass"	, "Byp"},
            {"Connector"	, "Con"},
            {"Extended"	, "Exd"},
            {"Extension"	, "Exn"},
            {"Loop"	, "Lp"},
            {"Private"	, "Pvt"},
            {"Public"	, "Pub"},
            {"Scenic"	, "Scn"},
            {"Spur"	, "Spr"},
            {"Ramp"	, "Rmp"},
            {"Underpass"	, "Unp"},
            {"Overpass"	, "Ovp"},
        };

        // The Prefix_Canonical constant maps canonical TIGER/Line street type
        // prefixes to their abbreviations. This list is the subset of the list from
        // 2008 TIGER/Line technical documentation Appendix E that was extracted from
        // a TIGER/Line database import.
        public static Dictionary<string, string> Prefix_Canonical = new Dictionary<string, string>()
        {
           
                {"Arcade"                            , "Arc"},
                {"Autopista"                         , "Autopista"},
                {"Avenida"                           , "Ave"},
                {"Avenue"                            , "Ave"},
                {"Boulevard"                         , "Blvd"},
                {"Bulevar"                           , "Bulevar"},
                {"Bureau of Indian Affairs Highway"  , "BIA Hwy"},
                {"Bureau of Indian Affairs Road"     , "BIA Rd"},
                {"Bureau of Indian Affairs Route"    , "BIA Rte"},
                {"Bureau of Land Management Road"    , "BLM Rd"},
                {"Bypass"                            , "Byp"},
                {"Calle"                             , "Cll"},
                {"Calleja"                           , "Calleja"},
                {"Callejón"                          , "Callejón"},
                {"Caminito"                          , "Cmt"},
                {"Camino"                            , "Cam"},
                {"Carretera"                         , "Carr"},
                {"Cerrada"                           , "Cer"},
                {"Círculo"                           , "Cír"},
                {"Commons"                           , "Cmns"},
                {"Corte"                             , "Corte"},
                {"County Highway"                    , "Co Hwy"},
                {"County Lane"                       , "Co Ln"},
                {"County Road"                       , "Co Rd"},
                {"County Route"                      , "Co Rte"},
                {"County State Aid Highway"          , "Co St Aid Hwy"},
                {"County Trunk Highway"              , "Co Trunk Hwy"},
                {"County Trunk Road"                 , "Co Trunk Rd"},
                {"Court"                             , "Ct"},
                {"Delta Road"                        , "Delta Rd"},
                {"District of Columbia Highway"      , "DC Hwy"},
                {"Driveway"                          , "Driveway"},
                {"Entrada"                           , "Ent"},
                {"Expreso"                           , "Expreso"},
                {"Expressway"                        , "Expy"},
                {"Farm Road"                         , "Farm Rd"},
                {"Farm-to-Market Road"               , "FM"},
                {"Fire Control Road"                 , "Fire Cntrl Rd"},
                {"Fire District Road"                , "Fire Dist Rd"},
                {"Fire Lane"                         , "Fire Ln"},
                {"Fire Road"                         , "Fire Rd"},
                {"Fire Route"                        , "Fire Rte"},
                {"Fire Trail"                        , "Fire Trl"},
                {"Forest Highway"                    , "Forest Hwy"},
                {"Forest Road"                       , "Forest Rd"},
                {"Forest Route"                      , "Forest Rte"},
                {"Forest Service Road"               , "FS Rd"},
                {"Highway"                           , "Hwy"},
                {"Indian Route"                      , "Indian Rte"},
                {"Indian Service Route"              , "Indian Svc Rte"},
                {"Interstate Highway"                , "I-"},
                {"Lane"                              , "Ln"},
                {"Logging Road"                      , "Logging Rd"},
                {"Loop"                              , "Loop"},
                {"National Forest Development Road"  , "Nat For Dev Rd"},
                {"Navajo Service Route"              , "Navajo Svc Rte"},
                {"Parish Road"                       , "Parish Rd"},
                {"Pasaje"                            , "Pasaje"},
                {"Paseo"                             , "Pso"},
                {"Passage"                           , "Psge"},
                {"Placita"                           , "Pla"},
                {"Plaza"                             , "Plz"},
                {"Point"                             , "Pt"},
                {"Puente"                            , "Puente"},
                {"Ranch Road"                        , "Ranch Rd"},
                {"Ranch to Market Road"              , "RM"},
                {"Reservation Highway"               , "Resvn Hwy"},
                {"Road"                              , "Rd"},
                {"Route"                             , "Rte"},
                {"Row"                               , "Row"},
                {"Rue"                               , "Rue"},
                {"Ruta"                              , "Ruta"},
                {"Sector"                            , "Sec"},
                {"Sendero"                           , "Sendero"},
                {"Service Road"                      , "Svc Rd"},
                {"Skyway"                            , "Skwy"},
                {"Square"                            , "Sq"},
                {"State Forest Service Road"         , "St FS Rd"},
                {"State Highway"                     , "State Hwy"},
                {"State Loop"                        , "State Loop"},
                {"State Road"                        , "State Rd"},
                {"State Route"                       , "State Rte"},
                {"State Spur"                        , "State Spur"},
                {"State Trunk Highway"               , "St Trunk Hwy"},
                {"Terrace"                           , "Ter"},
                {"Town Highway"                      , "Town Hwy"},
                {"Town Road"                         , "Town Rd"},
                {"Township Highway"                  , "Twp Hwy"},
                {"Township Road"                     , "Twp Rd"},
                {"Trail"                             , "Trl"},
                {"Tribal Road"                       , "Tribal Rd"},
                {"Tunnel"                            , "Tunl"},
                {"US Forest Service Highway"         , "USFS Hwy"},
                {"US Forest Service Road"            , "USFS Rd"},
                {"US Highway"                        , "US Hwy"},
                {"US Route"                          , "US Rte"},
                {"Vereda"                            , "Ver"},
                {"Via"                               , "Via"},
                {"Vista"                             , "Vis"},
            };

        // The Prefix_Alternate constant maps alternate prefix street types to
        // their canonical abbreviations. This list was merged in from the USPS
        // list at http://www.usps.com/ncsc/lookups/abbr_suffix.txt.
        public static Dictionary<string, string> Prefix_Alternate = new Dictionary<string, string>(){
            {"Av"			, "Ave"},
            {"Aven"			, "Ave"},
            {"Avenu"			, "Ave"},
            {"Avenue"			, "Ave"},
            {"Avn"			, "Ave"},
            {"Avnue"			, "Ave"},
            {"Boul"			, "Blvd"},
            {"Boulv"			, "Blvd"},
            {"Bypa"			, "Byp"},
            {"Bypas"			, "Byp"},
            {"Byps"			, "Byp"},
            {"Crt"			, "Ct"},
            {"Exp"			, "Expy"},
            {"Expr"			, "Expy"},
            {"Express"			, "Expy"},
            {"Expw"			, "Expy"},
            {"Highwy"			, "Hwy"},
            {"Hiway"			, "Hwy"},
            {"Hiwy"			, "Hwy"},
            {"Hway"			, "Hwy"},
            //"La"			, "Ln"}, // causes problems with Spanglish place names
            {"Lanes"			, "Ln"},
            {"Loops"			, "Loop"},
            {"Plza"			, "Plz"},
            {"Sqr"			, "Sq"},
            {"Sqre"			, "Sq"},
            {"Squ"			, "Sq"},
            {"Terr"			, "Ter"},
            {"Tr"			, "Trl"},
            {"Trails"			, "Trl"},
            {"Trls"			, "Trl"},
            {"Tunel"			, "Tunl"},
            {"Tunls"			, "Tunl"},
            {"Tunnels"			, "Tunl"},
            {"Tunnl"			, "Tunl"},
            {"Vdct"			, "Via"},
            {"Viadct"			, "Via"},
            {"Viaduct"			, "Via"},
            {"Vist"			, "Vis"},
            {"Vst"			, "Vis"},
            {"Vsta"			, "Vis"}
        };

        // The Prefix_Type constant merges the canonical prefix type abbreviations
        // with their USPS accepted alternates.

        public static Dictionary<string, string> Prefix_Type()
        {
            return Prefix_Canonical.Concat(Prefix_Alternate).GroupBy(d => d.Key).ToDictionary(d => d.Key, d => d.First().Value);
        }

        // The Suffix_Canonical constant maps canonical TIGER/Line street type
        // suffixes to their abbreviations. This list is the subset of the list from
        // 2008 TIGER/Line technical documentation Appendix E that was extracted from
        // a TIGER/Line database import.

        /* Since there are duplicates in this list, only the ones were commented which did NOt map to a 
         * value in the Suffix_Alternate list. */
        public static Dictionary<string, string> Suffix_Canonical = new Dictionary<string, string>()
        {
            //{"ALLEY", "ALLEE"},
            //{"ALLEY", "ALLY"},
            {"ALLEY", "ALY"},
            //{"ANNEX", "ANEX"},
            {"ANNEX", "ANX"},
            {"ARCADE", "ARC"},
            //{"AVENUE", "AV"},
            {"AVENUE", "AVE"},
            //{"AVENUE", "AVEN"},
            //{"AVENUE", "AVENU"},
            //{"AVENUE", "AVN"},
            //{"AVENUE", "AVNUE"},
            {"BAYOO", "BAYOU"},
            {"BEACH", "BCH"},
            {"BEND", "BND"},
            {"BLUFF", "BLF"},
            //{"BLUFF", "BLUF"},
            //{"BOTTOM", "BOT"},
            //{"BOTTOM", "BOTTM"},
            {"BOTTOM", "BTM"},
            {"BOULEVARD", "BLVD"},
            //{"BOULEVARD", "BOUL"},
            //{"BOULEVARD", "BOULV"},
            {"BRANCH", "BR"},
            //{"BRANCH", "BRNCH"},
            //{"BRIDGE", "BRDGE"},
            {"BRIDGE", "BRG"},
            {"BROOK", "BRK"},
            {"BYPASS", "BYP"},
            //{"BYPASS", "BYPA"},
            //{"BYPASS", "BYPAS"},
            //{"BYPASS", "BYPS"},
            //{"CAMP", "CMP"},
            {"CAMP", "CP"},
            //{"CANYON", "CANYN"},
            //{"CANYON", "CNYN"},
            {"CANYON", "CYN"},
            {"CAPE", "CPE"},
            //{"CAUSEWAY", "CAUSWAY"},
            {"CAUSEWAY", "CSWY"},
            //{"CENTER", "CEN"},
            //{"CENTER", "CENT"},
            //{"CENTER", "CENTR"},
            //{"CENTER", "CENTRE"},
            //{"CENTER", "CNTER"},
            //{"CENTER", "CNTR"},
            //{"CENTER", "CTR"},
            {"CIRCLE", "CIR"},
            //{"CIRCLE", "CIRC"},
            //{"CIRCLE", "CIRCL"},
            //{"CIRCLE", "CRCL"},
            //{"CIRCLE", "CRCLE"},
            {"CLIFF", "CLF"},
            {"CLIFFS", "CLFS"},
            {"CLUB", "CLB"},
            {"CORNER", "COR"},
            {"CORNERS", "CORS"},
            {"COURSE", "CRSE"},
            //{"COURT", "CRT"},
            {"COURT", "CT"},
            {"COURTS", "CT"},
            {"COVE", "CV"},
            //{"CREEK", "CK"},
            //{"CREEK", "CR"},
            {"CREEK", "CRK"},
            //{"CRESCENT", "CRECENT"},
            {"CRESCENT", "CRES"},
            //{"CRESCENT", "CRESENT"},
            //{"CRESCENT", "CRSCNT"},
            //{"CRESCENT", "CRSENT"},
            //{"CRESCENT", "CRSNT"},
            //{"CROSSING", "CRSSING"},
            //{"CROSSING", "CRSSNG"},
            {"CROSSING", "XING"},
            {"DALE", "DL"},
            {"DAM", "DM"},
            //{"DIVIDE", "DIV"},
            {"DIVIDE", "DV"},
            //{"DIVIDE", "DVD"},
            {"DRIVE", "DR"},
            //{"DRIVE", "DRIV"},
            //{"DRIVE", "DRV"},
            {"ESTATE", "EST"},
            {"ESTATES", "ESTS"},
            //{"EXPRESSWAY", "EXP"},
            //{"EXPRESSWAY", "EXPR"},
            //{"EXPRESSWAY", "EXPRESS"},
            //{"EXPRESSWAY", "EXPW"},
            //{"EXPRESSWAY", "EXPY"},
            {"EXTENSION", "EXT"},
            //{"EXTENSION", "EXTN"},
            //{"EXTENSION", "EXTNSN"},
            {"EXTENSIONS", "EXTS"},
            {"FALLS", "FLS"},
            //{"FERRY", "FRRY"},
            {"FERRY", "FRY"},
            {"FIELD", "FLD"},
            {"FIELDS", "FLDS"},
            {"FLAT", "FLT"},
            {"FLATS", "FLTS"},
            {"FORD", "FRD"},
            //{"FOREST", "FORESTS"},
            {"FOREST", "FRST"},
            //{"FORGE", "FORG"},
            {"FORGE", "FRG"},
            {"FORK", "FRK"},
            {"FORKS", "FRKS"},
            //{"FORT", "FRT"},
            {"FORT", "FT"},
            //{"FREEWAY", "FREEWY"},
            //{"FREEWAY", "FRWAY"},
            //{"FREEWAY", "FRWY"},
            {"FREEWAY", "FWY"},
            //{"GARDEN", "GARDN"},
            {"GARDEN", "GDN"},
            //{"GARDEN", "GRDEN"},
            //{"GARDEN", "GRDN"},
            {"GARDENS", "GDNS"},
            //{"GARDENS", "GRDNS"},
            //{"GATEWAY", "GATEWY"},
            //{"GATEWAY", "GATWAY"},
            //{"GATEWAY", "GTWAY"},
            {"GATEWAY", "GTWY"},
            {"GLEN", "GLN"},
            {"GREEN", "GRN"},
            //{"GROVE", "GROV"},
            {"GROVE", "GRV"},
            //{"HARBOR", "HARB"},
            //{"HARBOR", "HARBR"},
            {"HARBOR", "HBR"},
            //{"HARBOR", "HRBOR"},
            //{"HAVEN", "HAVN"},
            {"HAVEN", "HVN"},
            //{"HEIGHTS", "HEIGHT"},
            //{"HEIGHTS", "HGTS"},
            //{"HEIGHTS", "HT"},
            {"HEIGHTS", "HTS"},
            //{"HIGHWAY", "HIGHWY"},
            //{"HIGHWAY", "HIWAY"},
            //{"HIGHWAY", "HIWY"},
            //{"HIGHWAY", "HWAY"},
            {"HIGHWAY", "HWY"},
            {"HILL", "HL"},
            {"HILLS", "HLS"},
            //{"HOLLOW", "HLLW"},
            //{"HOLLOW", "HOLLOWS"},
            {"HOLLOW", "HOLW"},
            //{"HOLLOW", "HOLWS"},
            {"INLET", "INLT"},
            {"ISLAND", "IS"},
            //{"ISLAND", "ISLND"},
            //{"ISLANDS", "ISLNDS"},
            {"ISLANDS", "ISS"},
            {"ISLE", "ISLES"},
            {"JUNCTION", "JCT"},
            //{"JUNCTION", "JCTION"},
            //{"JUNCTION", "JCTN"},
            //{"JUNCTION", "JUNCTN"},
            //{"JUNCTION", "JUNCTON"},
            //{"JUNCTIONS", "JCTNS"},
            //{"JUNCTIONS", "JCTS"},
            {"KEY", "KY"},
            {"KEYS", "KYS"},
            {"KNOLL", "KNL"},
            //{"KNOLL", "KNOL"},
            {"KNOLLS", "KNLS"},
            {"LAKE", "LK"},
            {"LAKES", "LKS"},
            {"LANDING", "LNDG"},
            //{"LANDING", "LNDNG"},
            //{"LANE", "LA"},
            //{"LANE", "LANES"},
            {"LANE", "LN"},
            {"LIGHT", "LGT"},
            {"LOAF", "LF"},
            {"LOCK", "LCK"},
            {"LOCKS", "LCKS"},
            {"LODGE", "LDG"},
            //{"LODGE", "LDGE"},
            //{"LODGE", "LODG"},
            {"LOOP", "LOOPS"},
            {"MANOR", "MNR"},
            {"MANORS", "MNRS"},
            {"MEADOW", "MDW"},
            {"MEADOWS", "MDWS"},
            //{"MEADOWS", "MEDOWS"},
            {"MILL", "ML"},
            {"MILLS", "MLS"},
            //{"MISSION", "MISSN"},
            {"MISSION", "MSN"},
            //{"MISSION", "MSSN"},
            //{"MOUNT", "MNT"},
            {"MOUNT", "MT"},
            //{"MOUNTAIN", "MNTAIN"},
            //{"MOUNTAIN", "MNTN"},
            //{"MOUNTAIN", "MOUNTIN"},
            //{"MOUNTAIN", "MTIN"},
            {"MOUNTAIN", "MTN"},
            {"MOUNTAINS", "MNTNS"},
            {"NECK", "NCK"},
            {"ORCHARD", "ORCH"},
            //{"ORCHARD", "ORCHRD"},
            {"OVAL", "OVL"},
            {"PARK", "PK"},
            //{"PARK", "PRK"},
            //{"PARKWAY", "PARKWY"},
            //{"PARKWAY", "PKWAY"},
            {"PARKWAY", "PKWY"},
            //{"PARKWAY", "PKY"},
            {"PARKWAYS", "PKWYS"},
            {"PATH", "PATHS"},
            {"PIKE", "PIKES"},
            {"PINES", "PNES"},
            {"PLACE", "PL"},
            {"PLAIN", "PLN"},
            //{"PLAINS", "PLAINES"},
            {"PLAINS", "PLNS"},
            {"PLAZA", "PLZ"},
            //{"PLAZA", "PLZA"},
            {"POINT", "PT"},
            {"POINTS", "PTS"},
            {"PORT", "PRT"},
            {"PORTS", "PRTS"},
            {"PRAIRIE", "PR"},
            //{"PRAIRIE", "PRARIE"},
            //{"PRAIRIE", "PRR"},
            //{"RADIAL", "RAD"},
            //{"RADIAL", "RADIEL"},
            {"RADIAL", "RADL"},
            //{"RANCH", "RANCHES"},
            {"RANCH", "RNCH"},
            //{"RANCH", "RNCHS"},
            {"RAPID", "RPD"},
            {"RAPIDS", "RPDS"},
            {"REST", "RST"},
            {"RIDGE", "RDG"},
            //{"RIDGE", "RDGE"},
            {"RIDGES", "RDGS"},
            {"RIVER", "RIV"},
            //{"RIVER", "RIVR"},
            //{"RIVER", "RVR"},
            {"ROAD", "RD"},
            {"ROADS", "RDS"},
            {"SHOAL", "SHL"},
            {"SHOALS", "SHLS"},
            //{"SHORE", "SHOAR"},
            {"SHORE", "SHR"},
            //{"SHORES", "SHOARS"},
            {"SHORES", "SHRS"},
            {"SPRING", "SPG"},
            //{"SPRING", "SPNG"},
            //{"SPRING", "SPRNG"},
            {"SPRINGS", "SPGS"},
            //{"SPRINGS", "SPNGS"},
            //{"SPRINGS", "SPRNGS"},
            {"SQUARE", "SQ"},
            //{"SQUARE", "SQR"},
            //{"SQUARE", "SQRE"},
            //{"SQUARE", "SQU"},
            {"SQUARES", "SQRS"},
            {"STATION", "STA"},
            //{"STATION", "STATN"},
            //{"STATION", "STN"},
            {"STRAVENUE", "STRA"},
            //{"STRAVENUE", "STRAV"},
            //{"STRAVENUE", "STRAVE"},
            //{"STRAVENUE", "STRAVEN"},
            //{"STRAVENUE", "STRAVN"},
            //{"STRAVENUE", "STRVN"},
            //{"STRAVENUE", "STRVNUE"},
            //{"STREAM", "STREME"},
            {"STREAM", "STRM"},
            {"STREET", "ST"},
            //{"STREET", "STR"},
            //{"STREET", "STRT"},
            {"SUMMIT", "SMT"},
            //{"SUMMIT", "SUMIT"},
            //{"SUMMIT", "SUMITT"},
            {"TERRACE", "TER"},
            //{"TERRACE", "TERR"},
            //{"TRACE", "TRACES"},
            {"TRACE", "TRCE"},
            //{"TRACK", "TRACKS"},
            {"TRACK", "TRAK"},
            //{"TRACK", "TRK"},
            //{"TRACK", "TRKS"},
            {"TRAFFICWAY", "TRFY"},
            //{"TRAIL", "TR"},
            //{"TRAIL", "TRAILS"},
            {"TRAIL", "TRL"},
            //{"TRAIL", "TRLS"},
            //{"TUNNEL", "TUNEL"},
            {"TUNNEL", "TUNL"},
            //{"TUNNEL", "TUNLS"},
            //{"TUNNEL", "TUNNELS"},
            //{"TUNNEL", "TUNNL"},
            //{"TURNPIKE", "TPK"},
            {"TURNPIKE", "TPKE"},
            //{"TURNPIKE", "TRNPK"},
            //{"TURNPIKE", "TRPK"},
            //{"TURNPIKE", "TURNPK"},
            {"UNION", "UN"},
            //{"VALLEY", "VALLY"},
            //{"VALLEY", "VLLY"},
            {"VALLEY", "VLY"},
            {"VALLEYS", "VLYS"},
            //{"VIADUCT", "VDCT"},
            {"VIADUCT", "VIA"},
            //{"VIADUCT", "VIADCT"},
            {"VIEW", "VW"},
            {"VIEWS", "VWS"},
            //{"VILLAGE", "VILL"},
            //{"VILLAGE", "VILLAG"},
            //{"VILLAGE", "VILLG"},
            //{"VILLAGE", "VILLIAGE"},
            {"VILLAGE", "VLG"},
            {"VILLAGES", "VLGS"},
            {"VILLE", "VL"},
            {"VISTA", "VIS"},
            //{"VISTA", "VIST"},
            //{"VISTA", "VST"},
            //{"VISTA", "VSTA"},
            {"WAY", "WY"},
            {"WELLS", "WLS"},
        };

        // The Suffix_Alternate constant maps alternate suffix street types to
        // their canonical abbreviations. This list was merged in from the USPS
        // list at http://www.usps.com/ncsc/lookups/abbr_suffix.txt.
        public static Dictionary<string, string> Suffix_Alternate = new Dictionary<string, string>()
        {
            {"ALLEE", "ALY"},
            {"ALLEY", "ALY"},
            {"ALLY", "ALY"},
            {"ANEX", "ANX"},
            {"ANNEX", "ANX"},
            {"ARCADE", "ARC"},
            {"AV", "AVE"},
            {"AVEN", "AVE"},
            {"AVENU", "AVE"},
            {"AVENUE", "AVE"},
            {"AVN", "AVE"},
            {"AVNUE", "AVE"},
            {"BAYOO", "BYU"},
            {"BAYOU", "BYU"},
            {"BEACH", "BCH"},
            {"BEND", "BND"},
            {"BLUF", "BLF"},
            {"BLUFF", "BLF"},
            {"BLUFFS", "BLFS"},
            {"BOT", "BTM"},
            {"BOTTM", "BTM"},
            {"BOTTOM", "BTM"},
            {"BOUL", "BLVD"},
            {"BOULEVARD", "BLVD"},
            {"BOULV", "BLVD"},
            {"BRANCH", "BR"},
            {"BRNCH", "BR"},
            {"BRDGE", "BRG"},
            {"BRIDGE", "BRG"},
            {"BROOK", "BRK"},
            {"BROOKS", "BRKS"},
            {"BURG", "BG"},
            {"BURGS", "BGS"},
            {"BYPA", "BYP"},
            {"BYPAS", "BYP"},
            {"BYPASS", "BYP"},
            {"BYPS", "BYP"},
            {"CAMP", "CP"},
            {"CMP", "CP"},
            {"CANYN", "CYN"},
            {"CANYON", "CYN"},
            {"CNYN", "CYN"},
            {"CAPE", "CPE"},
            {"CAUSEWAY", "CSWY"},
            {"CAUSWAY", "CSWY"},
            {"CEN", "CTR"},
            {"CENT", "CTR"},
            {"CENTER", "CTR"},
            {"CENTR", "CTR"},
            {"CENTRE", "CTR"},
            {"CNTER", "CTR"},
            {"CNTR", "CTR"},
            {"CENTERS", "CTRS"},
            {"CIRC", "CIR"},
            {"CIRCL", "CIR"},
            {"CIRCLE", "CIR"},
            {"CRCL", "CIR"},
            {"CRCLE", "CIR"},
            {"CIRCLES", "CIRS"},
            {"CLIFF", "CLF"},
            {"CLIFFS", "CLFS"},
            {"CLUB", "CLB"},
            {"COMMON", "CMN"},
            {"CORNER", "COR"},
            {"CORNERS", "CORS"},
            {"COURSE", "CRSE"},
            {"COURT", "CT"},
            {"CRT", "CT"},
            {"COURTS", "CTS"},
            {"CT", "CTS"},
            {"COVE", "CV"},
            {"COVES", "CVS"},
            {"CK", "CRK"},
            {"CR", "CRK"},
            {"CREEK", "CRK"},
            {"CRECENT", "CRES"},
            {"CRESCENT", "CRES"},
            {"CRESENT", "CRES"},
            {"CRSCNT", "CRES"},
            {"CRSENT", "CRES"},
            {"CRSNT", "CRES"},
            {"CREST", "CRST"},
            {"CROSSING", "XING"},
            {"CRSSING", "XING"},
            {"CRSSNG", "XING"},
            {"CROSSROAD", "XRD"},
            {"CURVE", "CURV"},
            {"DALE", "DL"},
            {"DAM", "DM"},
            {"DIV", "DV"},
            {"DIVIDE", "DV"},
            {"DVD", "DV"},
            {"DRIV", "DR"},
            {"DRIVE", "DR"},
            {"DRV", "DR"},
            {"DRIVES", "DRS"},
            {"ESTATE", "EST"},
            {"ESTATES", "ESTS"},
            {"EXP", "EXPY"},
            {"EXPR", "EXPY"},
            {"EXPRESS", "EXPY"},
            {"EXPRESSWAY", "EXPY"},
            {"EXPW", "EXPY"},
            {"EXTENSION", "EXT"},
            {"EXTN", "EXT"},
            {"EXTNSN", "EXT"},
            {"EXTENSIONS", "EXTS"},
            {"FALLS", "FLS"},
            {"FERRY", "FRY"},
            {"FRRY", "FRY"},
            {"FIELD", "FLD"},
            {"FIELDS", "FLDS"},
            {"FLAT", "FLT"},
            {"FLATS", "FLTS"},
            {"FORD", "FRD"},
            {"FORDS", "FRDS"},
            {"FOREST", "FRST"},
            {"FORESTS", "FRST"},
            {"FORG", "FRG"},
            {"FORGE", "FRG"},
            {"FORGES", "FRGS"},
            {"FORK", "FRK"},
            {"FORKS", "FRKS"},
            {"FORT", "FT"},
            {"FRT", "FT"},
            {"FREEWAY", "FWY"},
            {"FREEWY", "FWY"},
            {"FRWAY", "FWY"},
            {"FRWY", "FWY"},
            {"GARDEN", "GDN"},
            {"GARDN", "GDN"},
            {"GRDEN", "GDN"},
            {"GRDN", "GDN"},
            {"GARDENS", "GDNS"},
            {"GRDNS", "GDNS"},
            {"GATEWAY", "GTWY"},
            {"GATEWY", "GTWY"},
            {"GATWAY", "GTWY"},
            {"GTWAY", "GTWY"},
            {"GLEN", "GLN"},
            {"GLENS", "GLNS"},
            {"GREEN", "GRN"},
            {"GREENS", "GRNS"},
            {"GROV", "GRV"},
            {"GROVE", "GRV"},
            {"GROVES", "GRVS"},
            {"HARB", "HBR"},
            {"HARBOR", "HBR"},
            {"HARBR", "HBR"},
            {"HRBOR", "HBR"},
            {"HARBORS", "HBRS"},
            {"HAVEN", "HVN"},
            {"HAVN", "HVN"},
            {"HEIGHT", "HTS"},
            {"HEIGHTS", "HTS"},
            {"HGTS", "HTS"},
            {"HT", "HTS"},
            {"HIGHWAY", "HWY"},
            {"HIGHWY", "HWY"},
            {"HIWAY", "HWY"},
            {"HIWY", "HWY"},
            {"HWAY", "HWY"},
            {"HILL", "HL"},
            {"HILLS", "HLS"},
            {"HLLW", "HOLW"},
            {"HOLLOW", "HOLW"},
            {"HOLLOWS", "HOLW"},
            {"HOLWS", "HOLW"},
            {"INLET", "INLT"},
            {"ISLAND", "IS"},
            {"ISLND", "IS"},
            {"ISLANDS", "ISS"},
            {"ISLNDS", "ISS"},
            {"ISLES", "ISLE"},
            {"JCTION", "JCT"},
            {"JCTN", "JCT"},
            {"JUNCTION", "JCT"},
            {"JUNCTN", "JCT"},
            {"JUNCTON", "JCT"},
            {"JCTNS", "JCTS"},
            {"JUNCTIONS", "JCTS"},
            {"KEY", "KY"},
            {"KEYS", "KYS"},
            {"KNOL", "KNL"},
            {"KNOLL", "KNL"},
            {"KNOLLS", "KNLS"},
            {"LAKE", "LK"},
            {"LAKES", "LKS"},
            {"LANDING", "LNDG"},
            {"LNDNG", "LNDG"},
            {"LA", "LN"},
            {"LANE", "LN"},
            {"LANES", "LN"},
            {"LIGHT", "LGT"},
            {"LIGHTS", "LGTS"},
            {"LOAF", "LF"},
            {"LOCK", "LCK"},
            {"LOCKS", "LCKS"},
            {"LDGE", "LDG"},
            {"LODG", "LDG"},
            {"LODGE", "LDG"},
            {"LOOPS", "LOOP"},
            {"MANOR", "MNR"},
            {"MANORS", "MNRS"},
            {"MEADOW", "MDW"},
            {"MEADOWS", "MDWS"},
            {"MEDOWS", "MDWS"},
            {"MILL", "ML"},
            {"MILLS", "MLS"},
            {"MISSION", "MSN"},
            {"MISSN", "MSN"},
            {"MSSN", "MSN"},
            {"MOTORWAY", "MTWY"},
            {"MNT", "MT"},
            {"MOUNT", "MT"},
            {"MNTAIN", "MTN"},
            {"MNTN", "MTN"},
            {"MOUNTAIN", "MTN"},
            {"MOUNTIN", "MTN"},
            {"MTIN", "MTN"},
            {"MNTNS", "MTNS"},
            {"MOUNTAINS", "MTNS"},
            {"NECK", "NCK"},
            {"ORCHARD", "ORCH"},
            {"ORCHRD", "ORCH"},
            {"OVL", "OVAL"},
            {"OVERPASS", "OPAS"},
            {"PK", "PARK"},
            {"PRK", "PARK"},
            {"PARKS", "PARK"},
            {"PARKWAY", "PKWY"},
            {"PARKWY", "PKWY"},
            {"PKWAY", "PKWY"},
            {"PKY", "PKWY"},
            {"PARKWAYS", "PKWY"},
            {"PKWYS", "PKWY"},
            {"PASSAGE", "PSGE"},
            {"PATHS", "PATH"},
            {"PIKES", "PIKE"},
            {"PINE", "PNE"},
            {"PINES", "PNES"},
            {"PLACE", "PL"},
            {"PLAIN", "PLN"},
            {"PLAINES", "PLNS"},
            {"PLAINS", "PLNS"},
            {"PLAZA", "PLZ"},
            {"PLZA", "PLZ"},
            {"POINT", "PT"},
            {"POINTS", "PTS"},
            {"PORT", "PRT"},
            {"PORTS", "PRTS"},
            {"PRAIRIE", "PR"},
            {"PRARIE", "PR"},
            {"PRR", "PR"},
            {"RAD", "RADL"},
            {"RADIAL", "RADL"},
            {"RADIEL", "RADL"},
            {"RANCH", "RNCH"},
            {"RANCHES", "RNCH"},
            {"RNCHS", "RNCH"},
            {"RAPID", "RPD"},
            {"RAPIDS", "RPDS"},
            {"REST", "RST"},
            {"RDGE", "RDG"},
            {"RIDGE", "RDG"},
            {"RIDGES", "RDGS"},
            {"RIVER", "RIV"},
            {"RIVR", "RIV"},
            {"RVR", "RIV"},
            {"ROAD", "RD"},
            {"ROADS", "RDS"},
            {"ROUTE", "RTE"},
            {"SHOAL", "SHL"},
            {"SHOALS", "SHLS"},
            {"SHOAR", "SHR"},
            {"SHORE", "SHR"},
            {"SHOARS", "SHRS"},
            {"SHORES", "SHRS"},
            {"SKYWAY", "SKWY"},
            {"SPNG", "SPG"},
            {"SPRING", "SPG"},
            {"SPRNG", "SPG"},
            {"SPNGS", "SPGS"},
            {"SPRINGS", "SPGS"},
            {"SPRNGS", "SPGS"},
            {"SPURS", "SPUR"},
            {"SQR", "SQ"},
            {"SQRE", "SQ"},
            {"SQU", "SQ"},
            {"SQUARE", "SQ"},
            {"SQRS", "SQS"},
            {"SQUARES", "SQS"},
            {"STATION", "STA"},
            {"STATN", "STA"},
            {"STN", "STA"},
            {"STRAV", "STRA"},
            {"STRAVE", "STRA"},
            {"STRAVEN", "STRA"},
            {"STRAVENUE", "STRA"},
            {"STRAVN", "STRA"},
            {"STRVN", "STRA"},
            {"STRVNUE", "STRA"},
            {"STREAM", "STRM"},
            {"STREME", "STRM"},
            {"STR", "ST"},
            {"STREET", "ST"},
            {"STRT", "ST"},
            {"STREETS", "STS"},
            {"SUMIT", "SMT"},
            {"SUMITT", "SMT"},
            {"SUMMIT", "SMT"},
            {"TERR", "TER"},
            {"TERRACE", "TER"},
            {"THROUGHWAY", "TRWY"},
            {"TRACE", "TRCE"},
            {"TRACES", "TRCE"},
            {"TRACK", "TRAK"},
            {"TRACKS", "TRAK"},
            {"TRK", "TRAK"},
            {"TRKS", "TRAK"},
            {"TRAFFICWAY", "TRFY"},
            {"TR", "TRL"},
            {"TRAIL", "TRL"},
            {"TRAILS", "TRL"},
            {"TRLS", "TRL"},
            {"TUNEL", "TUNL"},
            {"TUNLS", "TUNL"},
            {"TUNNEL", "TUNL"},
            {"TUNNELS", "TUNL"},
            {"TUNNL", "TUNL"},
            {"TPK", "TPKE"},
            {"TRNPK", "TPKE"},
            {"TRPK", "TPKE"},
            {"TURNPIKE", "TPKE"},
            {"TURNPK", "TPKE"},
            {"UNDERPASS", "UPAS"},
            {"UNION", "UN"},
            {"UNIONS", "UNS"},
            {"VALLEY", "VLY"},
            {"VALLY", "VLY"},
            {"VLLY", "VLY"},
            {"VALLEYS", "VLYS"},
            {"VDCT", "VIA"},
            {"VIADCT", "VIA"},
            {"VIADUCT", "VIA"},
            {"VIEW", "VW"},
            {"VIEWS", "VWS"},
            {"VILL", "VLG"},
            {"VILLAG", "VLG"},
            {"VILLAGE", "VLG"},
            {"VILLG", "VLG"},
            {"VILLIAGE", "VLG"},
            {"VILLAGES", "VLGS"},
            {"VILLE", "VL"},
            {"VIST", "VIS"},
            {"VISTA", "VIS"},
            {"VST", "VIS"},
            {"VSTA", "VIS"},
            {"WALKS", "WALK"},
            {"WY", "WAY"},
            {"WELL", "WL"},
            {"WELLS", "WLS"},

        };

        // The Suffix_Type constant merges the canonical suffix type abbreviations
        // with their USPS accepted alternates.

        public static Dictionary<string, string> Suffix_Type()
        {
            return Suffix_Canonical.Concat(Suffix_Alternate).GroupBy(d => d.Key).ToDictionary(d => d.Key, d => d.First().Value);
        }

        // The Unit_Type constant lists acceptable USPS unit type abbreviations
        // from http://www.usps.com/ncsc/lookups/abbr_sud.txt.
        public static Dictionary<string, string> Unit_Type = new Dictionary<string, string>()
        {
            {"Apartment"	, "Apt"},
            {"Basement"	, "Bsmt"},
            {"Building"	, "Bldg"},
            {"Department", "Dept"},
            {"Floor"	, "Fl"},
            {"Front"	, "Frnt"},
            {"Hangar"	, "Hngr"},
            {"Lobby"	, "Lbby"},
            {"Lot"	, "Lot"},
            {"Lower"	, "Lowr"},
            {"Office"	, "Ofc"},
            {"Penthouse"	, "Ph"},
            {"Pier"	, "Pier"},
            {"Rear"	, "Rear"},
            {"Room"	, "Rm"},
            {"Side"	, "Side"},
            {"Slip"	, "Slip"},
            {"Space"	, "Spc"},
            {"Stop"	, "Stop"},
            {"Suite"	, "Ste"},
            {"Trailer"	, "Trlr"},
            {"Unit"	, "Unit"},
            {"Upper"	, "Uppr"},
        };

        public static Dictionary<string, string> Std_Abbr()
        {
            return Prefix_Qualifier.Concat(Suffix_Qualifier).Concat(Prefix_Type()).Concat(Suffix_Type()).GroupBy(d => d.Key).ToDictionary(d => d.Key, d => d.First().Value);
        }

        // The Name_Abbr constant maps common toponym abbreviations to their
        // full word equivalents. This list was constructed partly by hand}, and
        // partly by matching USPS alternate abbreviations with feature names
        // found in the TIGER/Line dataset.
        public static Dictionary<string, string> Name_Abbr = new Dictionary<string, string>()
        {
            {"Av"	, "Avenue"},
            {"Ave"	, "Avenue"},
            {"Blvd"	, "Boulevard"},
            {"Bot"	, "Bottom"},
            {"Boul"	, "Boulevard"},
            {"Boulv"	, "Boulevard"},
            {"Br"	, "Branch"},
            {"Brg"	, "Bridge"},
            {"Canyn"	, "Canyon"},
            {"Cen"	, "Center"},
            {"Cent"	, "Center"},
            {"Cir"	, "Circle"},
            {"Circ"	, "Circle"},
            {"Ck"	, "Creek"},
            {"Cnter"	, "Center"},
            {"Cntr"	, "Center"},
            {"Cnyn"	, "Canyon"},
            {"Cor"	, "Corner"},
            {"Cors"	, "Corners"},
            {"Cp"	, "Camp"},
            {"Cr"	, "Creek"},
            {"Crcl"	, "Circle"},
            {"Crcle"	, "Circle"},
            {"Cres"	, "Crescent"},
            {"Crscnt"	, "Crescent"},
            {"Ct"	, "Court"},
            {"Ctr"	, "Center"},
            {"Cts"	, "Courts"},
            {"Cyn"	, "Canyon"},
            {"Div"	, "Divide"},
            {"Dr"	, "Drive"},
            {"Dv"	, "Divide"},
            {"Est"	, "Estate"},
            {"Ests"	, "Estates"},
            {"Ext"	, "Extension"},
            {"Extn"	, "Extension"},
            {"Extnsn"	, "Extension"},
            {"Forests"	, "Forest"},
            {"Forg"	, "Forge"},
            {"Frg"	, "Forge"},
            {"Ft"	, "Fort"},
            {"Gatewy"	, "Gateway"},
            {"Gdn"	, "Garden"},
            {"Gdns"	, "Gardens"},
            {"Gtwy"	, "Gateway"},
            {"Harb"	, "Harbor"},
            {"Hbr"	, "Harbor"},
            {"Height"	, "Heights"},
            {"Hgts"	, "Heights"},
            {"Highwy"	, "Highway"},
            {"Hiway"	, "Highway"},
            {"Hiwy"	, "Highway"},
            {"Holws"	, "Hollow"},
            {"Ht"	, "Heights"},
            {"Hway"	, "Highway"},
            {"Hwy"	, "Highway"},
            {"Is"	, "Island"},
            {"Iss"	, "Islands"},
            {"Jct"	, "Junction"},
            {"Jction"	, "Junction"},
            {"Jctn"	, "Junction"},
            {"Junctn"	, "Junction"},
            {"Juncton"	, "Junction"},
            {"Ldg"	, "Lodge"},
            {"Lgt"	, "Light"},
            {"Lndg"	, "Landing"},
            {"Lodg"	, "Lodge"},
            {"Loops"	, "Loop"},
            {"Mt"	, "Mount"},
            {"Mtin"	, "Mountain"},
            {"Mtn"	, "Mountain"},
            {"Orch"	, "Orchard"},
            {"Parkwy"	, "Parkway"},
            {"Pk"	, "Park"},
            {"Pkway"	, "Parkway"},
            {"Pkwy"	, "Parkway"},
            {"Pky"	, "Parkway"},
            {"Pl"	, "Place"},
            {"Pnes"	, "Pines"},
            {"Pr"	, "Prairie"},
            {"Prr"	, "Prairie"},
            {"Pt"	, "Point"},
            {"Pts"	, "Points"},
            {"Rdg"	, "Ridge"},
            {"Riv"	, "River"},
            {"Rnchs"	, "Ranch"},
            {"Spg"	, "Spring"},
            {"Spgs"	, "Springs"},
            {"Spng"	, "Spring"},
            {"Spngs"	, "Springs"},
            {"Sq"	, "Square"},
            {"Squ"	, "Square"},
            //    "St"	, "Saint"},
            {"Sta"	, "Station"},
            {"Statn"	, "Station"},
            {"Ste"	, "Sainte"},
            {"Stn"	, "Station"},
            {"Str"	, "Street"},
            {"Ter"	, "Terrace"},
            {"Terr"	, "Terrace"},
            {"Tpk"	, "Turnpike"},
            {"Tpke"	, "Turnpike"},
            {"Tr"	, "Trail"},
            {"Trls"	, "Trail"},
            {"Trpk"	, "Turnpike"},
            {"Tunls"	, "Tunnel"},
            {"Un"	, "Union"},
            {"Vill"	, "Village"},
            {"Villag"	, "Village"},
            {"Villg"	, "Village"},
            {"Vis"	, "Vista"},
            {"Vlg"	, "Village"},
            {"Vlgs"	, "Villages"},
            {"Wls"	, "Wells"},
            {"Wy"	, "Way"},
            {"Xing"	, "Crossing"},
        };


        public static Dictionary<string, string> State = new Dictionary<string, string>()
        {
            {"Alabama", "AL"},
            {"Alaska", "AK"},
            {"American Samoa", "AS"},
            {"Arizona", "AZ"},
            {"Arkansas", "AR"},
            {"California", "CA"},
            {"Colorado", "CO"},
            {"Connecticut", "CT"},
            {"Delaware", "DE"},
            {"District of Columbia", "DC"},
            {"Federated States of Micronesia", "FM"},
            {"Florida", "FL"},
            {"Georgia", "GA"},
            {"Guam", "GU"},
            {"Hawaii", "HI"},
            {"Idaho", "ID"},
            {"Illinois", "IL"},
            {"Indiana", "IN"},
            {"Iowa", "IA"},
            {"Kansas", "KS"},
            {"Kentucky", "KY"},
            {"Louisiana", "LA"},
            {"Maine", "ME"},
            {"Marshall Islands", "MH"},
            {"Maryland", "MD"},
            {"Massachusetts", "MA"},
            {"Michigan", "MI"},
            {"Minnesota", "MN"},
            {"Mississippi", "MS"},
            {"Missouri", "MO"},
            {"Montana", "MT"},
            {"Nebraska", "NE"},
            {"Nevada", "NV"},
            {"New Hampshire", "NH"},
            {"New Jersey", "NJ"},
            {"New Mexico", "NM"},
            {"New York", "NY"},
            {"North Carolina", "NC"},
            {"North Dakota", "ND"},
            {"Northern Mariana Islands", "MP"},
            {"Ohio", "OH"},
            {"Oklahoma", "OK"},
            {"Oregon", "OR"},
            {"Palau", "PW"},
            {"Pennsylvania", "PA"},
            {"Puerto Rico", "PR"},
            {"Rhode Island", "RI"},
            {"South Carolina", "SC"},
            {"South Dakota", "SD"},
            {"Tennessee", "TN"},
            {"Texas", "TX"},
            {"Utah", "UT"},
            {"Vermont", "VT"},
            {"Virgin Islands", "VI"},
            {"Virginia", "VA"},
            {"Washington", "WA"},
            {"West Virginia", "WV"},
            {"Wisconsin", "WI"},
            {"Wyoming", "WY"}
        };

    }
}